Repository ttekglobal/redash, pull requests merged in 2020-11, with the labels that each got.

#11 Stack chart
  client/app/assets/less/dark.less
  package-lock.json
  package.json
  viz-lib/package.json
  viz-lib/src/visualizations/chart/Editor/ColumnMappingSelect.jsx
  viz-lib/src/visualizations/chart/Editor/GeneralSettings.jsx
  viz-lib/src/visualizations/chart/Renderer/initChart.js
  viz-lib/src/visualizations/chart/plotly/index.js
  viz-lib/src/visualizations/chart/plotly/prepareGroupedData.js
  viz-lib/src/visualizations/chart/plotly/prepareGroupedLayout.js
  yarn.lock
Labels: enhancement

#13 Change branch build to develop
  .github/workflows/test.yml
  helm/.circleci/config.yml
  helm/.gitignore
  helm/.helmignore
  helm/.pre-commit-config.yaml
  helm/.prettierignore
  helm/.restyled.yaml
  helm/CHANGELOG.md
  helm/CONTRIBUTING.md
  helm/Chart.yaml
  helm/LICENSE
  helm/README.md
  helm/README.md.gotmpl
  helm/requirements.lock
  helm/requirements.yaml
  helm/scripts/update-env-config.py
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/adhocworker-deployment.yaml
  helm/templates/configmap.yaml
  helm/templates/genericworker-deployment.yaml
  helm/templates/hook-install-job.yaml
  helm/templates/hook-upgrade-job.yaml
  helm/templates/ingress.yaml
  helm/templates/scheduledworker-deployment.yaml
  helm/templates/scheduler-deployment.yaml
  helm/templates/secrets.yaml
  helm/templates/server-deployment.yaml
  helm/templates/service.yaml
  helm/templates/serviceaccount.yaml
  helm/templates/tests/test-connection.yaml
  helm/values.yaml
Labels: Deployment

#15 Stack chart
  viz-lib/src/visualizations/chart/Editor/GeneralSettings.jsx
  viz-lib/src/visualizations/chart/Renderer/initChart.js
Labels: bug

#17 Update token do
  .github/workflows/test.yml
  helm/requirements.yaml
  helm/values.yaml
Labels: Deployment

#19 Update helm value and github flow
  .github/workflows/test.yml
  helm/requirements.yaml
  helm/values.yaml
Labels: Deployment

#20 Fix tag image builder
  .github/workflows/test.yml
Labels: Deployment

#23 Update test.yml
  .github/workflows/test.yml
Labels: Deployment

#24 Update test.yml
  .github/workflows/test.yml
Labels: Deployment

#25 Update test.yml
  .github/workflows/test.yml
Labels: Deployment
